### ISSUE TITLE
basic refinerycms-ckeditor setup

### ISSUE THREAD

**Issue by boehmak** [botandrose/refinerycms-ckeditor#2] opened 2012-03-29 10:19 UTC
original email:

> Hi Micah,
> 
> I am trying to replace the wymeditor editor with the ckeditor through your refinerycms-ckeditor extension. 
> 
> Once I installed the gem with 'bundle install' I can only see a textfield without any editor. Thats a good sign, because the wymeditor editor is gone. But now I wonder what I would have to configure to get the basic ckeditor set up.
> 
> Do you have a simple demo refineycms app that would show what I would have to to change/override? 
> 
> I am fairly new to refinerycms and would appreciate your help.
> 
> Thank you.

Thank you for your response. I must have messed up some stuff while exploring. ~~I now created a new app from scratch and it worked right away.~~ Sorry for wasting your time. 

This searching gave me a rough insight into how extensions work. 

By the way I found a great tutorial about refinerycms and ckeditor. Guirec Corbel walkes you through building his blog with refinerycms. It is in french but google translation helps. 
http://guirec-corbel.heroku.com/blog/installation-de-refinerycms-partie-1

Thank you for having a word with me.

Here are the versions I used:
ruby 1.9.2p318
refinerycms (2.0.2)
refinerycms-ckeditor (0.1.2)

**Comment by boehmak** [comment] 2012-03-29 10:57
Actually it does not work. I was too fast with my response. I mixed up wymeditor and ckeditor. I just ran into the same problem as stated earlier. ~~I can't see any js errors.~~ The first time I run rails server I get two js errors. Later they disappear and the two files en.js and skin.js have no content.

Uncaught TypeError: Cannot set property 'en' of undefined (en.js:1)
Uncaught TypeError: Cannot set property 'refinery' of undefined (skin.js:1) 

Here are my exact steps:

refinerycms demo2
rails server
vi Gemfile (insert: gem 'refinerycms-ckeditor')
bundle install
rails server

I have ruby 1.9.2p318 installed using rvm. This is my Gemfile.lock https://gist.github.com/2249791

I put the basic setup online at https://github.com/proboapp/refinerycms_demo2

**Comment by botandrose** [comment] 2012-03-30 20:24
@proboapp thanks for putting up your setup, ive successfully used it to recreate the issue. investigating now...

**Comment by botandrose** [comment] 2012-03-30 20:53
@proboapp Fixed. Update your refinerycms-ckeditor version to 0.1.3, and it should work. Reopen this issue, if not!

Turns out the gem had an undeclared dependency on haml. I coded the replacement editor view partial in haml, and since we use haml on all of our sites, it worked fine. However, your fresh install didn't include haml, so the replacement view wasn't being recognized. I've converted the view over to erb, so it should work out of the box for everyone now, haml or not.

Thanks for the bug report!

**Comment by boehmak** [comment] 2012-03-31 18:24
Thanks for the update. 

But now half of the site is frozen. I cannot edit the textfield or click on the tabs. I spotted a suspicious css file with the chrome developer tool :-)

**data:text/css,**

**Comment by botandrose** [comment] 2012-03-31 20:31
If clicking on the tabs does nothing, I suspect a javascript error somewhere. Can you confirm?

**Comment by boehmak** [comment] 2012-04-01 07:11
I am sorry, but the chrome developer tool does not show me any javascript errors. I have the same basic setup and only changed the refinerycms-ckeditor gem to 0.1.3.

In the file __page_part_field.html.erb_ I think there is a closing div tag missing.
https://github.com/botandrose/refinerycms-ckeditor/blob/master/app/views/refinery/admin/pages/_page_part_field.html.erb#L36

**Comment by botandrose** [comment] 2012-04-02 22:11
@proboapp Hah, good catch! That's the perfect example of why I use haml. I've fixed the missing closing div, and now I'll try to see if I can reproduce your new problem.

**Comment by botandrose** [comment] 2012-04-02 22:23
@proboapp Confirmed. I'll see if I can figure out the source of the problem now. Thanks for providing the sample app to reproduce the error, it helps quite a bit!

**Comment by botandrose** [comment] 2012-04-02 22:47
@proboapp Fixed! Turns out that the css that comes out of the box with this gem had a few bugs. Released v0.1.4, which should fix your issues.

Closing. Reopen if you still are having problems!

**Closed as completed by botandrose** 2012-04-02 22:47 UTC
